# Generated by Django 5.1.4 on 2024-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_edited_at_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Drafe'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
